# not having apt-utils seems to not be a problem (we do get a warning tho)
# see https://stackoverflow.com/questions/51023312/docker-having-issues-installing-apt-utils

tasks:
  - name: FASM Task
    init: |
      sudo apt update
      #sudo apt upgrade
      #sudo apt install fasm_1.73.27-1_amd64.deb
      sudo apt install fasm
    command: make

vscode:
  extensions:
    - maziac.asm-code-lens
