# FIXME: no Formulae for FASM
# https://github.com/Homebrew/homebrew-core/blob/9e06aab2e51e2090316b1f4beb1c5664be5e3803/Formula/yasm.rb
# https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
# installing with apt instead...

tasks:
  - command: |
  # brew install fasm
      sudo apt update
      sudo apt -y install fasm
      make
      
vscode:
  extensions:
    - maziac.asm-code-lens
