# FIXME: no Formulae for FASM
# https://github.com/Homebrew/homebrew-core/blob/9e06aab2e51e2090316b1f4beb1c5664be5e3803/Formula/yasm.rb

tasks:
  - command: |
     # brew install fasm.x64
      make
      
vscode:
  extensions:
    - maziac.asm-code-lens
